name: Build on release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: 'v*' # Push events to matching v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        env:
          BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-disabled: true
          arguments: build
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Draft release ${{ github.ref }}
          body: Replace this text with the description of this release!
          draft: true
          prerelease: false
          files: |
            concoction-cmd/build/libs/*
            concoction-lib/build/libs/*
